### ISSUE TITLE
opening summary plots in python

### ISSUE THREAD

**Issue by Shrikantspatil** [equinor/ecl#367]
Hello everyone,

I am trying to open the summary plots after running SPE1CASE1 input deck, but I am getting following error.  Any help to resolve this issue will be highly appreciated !

```
ubuntu@ubuntu-xenial:~/opm-data-master/spe1$ python summaryplot WBHP:INJ WBHP:PROD WOPR:PROD WGPR:PROD WGIR:INJ SPE1CASE1.DATA
Traceback (most recent call last):
  File "summaryplot", line 58, in <module>
    from ecl.eclfile import EclFile
  File "/usr/lib/python2.7/dist-packages/ecl/__init__.py", line 121, in <module>
    from .util import EclVersion
  File "/usr/lib/python2.7/dist-packages/ecl/util/__init__.py", line 46, in <module>
    class UtilPrototype(Prototype):
  File "/usr/lib/python2.7/dist-packages/ecl/util/__init__.py", line 47, in UtilPrototype
    lib = ecl.load("libecl")
  File "/usr/lib/python2.7/dist-packages/ecl/__init__.py", line 118, in load
    return cwrapload(name, path=ecl_lib_path, so_version=ert_so_version)
  File "/usr/lib/python2.7/dist-packages/cwrap/clib.py", line 90, in load
    raise ImportError(error_msg)
ImportError:
Failed to load shared library:libecl

dlopen() error: libecl.so: cannot open shared object file: No such file or directory
```

The runtime linker has searched through the default location of shared
libraries, and also the locations mentioned in your LD_LIBRARY_PATH
variable. Your current LD_LIBRARY_PATH setting is:

   LD_LIBRARY_PATH:

You might need to update this variable?

ubuntu@ubuntu-xenial:~/opm-data-master/spe1$

**Comment by joakim-hove** [comment]
Well;

as the error message says the python module can not locate the underlying shared library `libecl.so` - and why is that is not immediately clear to me. If you find the location of the `libecl.so`file you can set the `LD_LIBRARY_PATH`variable to point there:

```bash
export LD_LIBRARY_PATH=/path/to/libecl/library
```

That being said something was slightly broken with the 2017.10 version of the libecl packages. For Python and plotting with `summaryplot` you can just download and build your own version; it is quite simple:
```bash
git clone git@github.com:Statoil/libecl
cd libecl
mkdir build ; cd build
cmake .. -DENABLE_PYTHON=ON -DCMAKE_INSTALL_PREFFIX=$HOME/libecl/install
make 
make install
```
Then you can set `PYTHONPATH=$HOME/llibecl/install/lib/python2.7/dist-packages` and things should work. 

The Python bindings in the libecl distribution are quite well maintained, and generally work well. However the `summaryplot` in opm-utilities is not equally well maintained; and you might have to make some changes there as well. I'd be happy to assist you.

For something more feature complete you could give Resinsight a try, that will also show 3D fields like pressure and saturations.

**Comment by pgdr** [comment]
Or perhaps `sudo make install` is simpler if you want to avoid path managing

**Comment by Shrikantspatil** [comment]
Thank you so much for the guidance !  I followed the above mentioned set of instructions, but i now i am getting a new error:

ubuntu@ubuntu-xenial:~/opm-data-master/spe1$ python summaryplot WBHP:INJ WBHP:PROD WOPR:PROD WGPR:PROD WGIR:INJ SPE1CASE1.DATA
Menu: 'q' = quit, 'r' = reload plots
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "summaryplot", line 344, in summaryplotter
    fig = pyplot.figure()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: no display name and no $DISPLAY environment variable


how can I fix this ?

Joakim,

I like ResInsight, but I am trying to automate the generation of graphs, so that with one command the system will display a list of graphs for me.  Can ResInsight do something like that ?

**Comment by dotfloat** [comment]
Closing due to age. Looks like a Linux environment issue rather than anything in libecl.
