### ISSUE TITLE
TestAreaContext deletes tmp dir and enters infinite loop

### ISSUE THREAD

**Issue by mortalisk** [equinor/ecl#648]
While working on [libres#653](https://github.com/equinor/libres/pull/653), we encountered this bug. When running pytest in the new test folder (job_runner) we created there, i.e. to run all the tests, TestAreaContext would consistently enter an infinite loop during construction. We don't know why, but this happens only with tests that are in the new folder python/tests/job_runner. It only happens when running pytest without specifying a test, thus letting it discover tests for itself. We have now used other means of creating a tmp working dir in those tests, but it should be possible to reproduce the error by trying to use TestAreaContext in some of those tests in libres.

It seems that the tmp dir that it creates and then chdirs to, is then deleted. After this, it tries to find the current working directory, which then fails with ENOENT. ENOENT is not handled, and the code enters a never ending loop. This happens in the function util_alloc_cwd() in util.c.

https://github.com/equinor/libecl/blob/e6d02534589d3ab0922d622a06e5adfd948ed3d1/lib/util/util.c#L694-L710

So, there are two issues it seems:

1. the tmp dir is for some reason deleted
2. the function util_alloc_cwd does not handle other errors than ERANGE, and thus enters a infinite loop befause of 1

**Comment by dotfloat** [comment]
https://man7.org/linux/man-pages/man2/getcwd.2.html

**Comment by mortalisk** [comment]
I was unable to reproduce the deleting of tmp dir issue. But I have at least removed the infinite loop issue in PR #776

**Comment by sondreso** [comment]
Should we close this now?
