### ISSUE TITLE
Problem obtaining ecl_summary app from "libecl"

### ISSUE THREAD

**Issue by ivanfe639** [equinor/ecl#703]
Hi, I'm trying to compile libecl library to obtain "ecl_summary" but I follow the steps posted and obtain an error, I was trying with the instructions by the video tutorial (https://www.youtube.com/watch?v=Qqy1vA1PSk8) too and can do the cmake, make and make install but I don't know where is the ecl_summary app. Thanks for your attention.

**Comment by dotfloat** [comment]
You need to add `-DBUILD_ECL_SUMMARY=ON` to the `cmake` command:

```
$ # We're inside libecl repository
$ mkdir build && cd build
$ cmake .. -DBUILD_ECL_SUMMARY=ON
$ make
$ sudo make install
```
