### ISSUE TITLE
Summary RESTART filepath limited to 72 characters

### ISSUE THREAD

**Issue by asnyv** [equinor/ecl#713]
`ecl.summary.EclSum` has a key to get the summary from the both the original case as well as the restart case by setting `include_restart=True`. 
The filepath is defined by the `RESTART` keyword in the `.DATA` file of the restart simulation deck, but it is also stored in the `.SMSPEC`.

Currently the `libecl` implementation silently ignores any path above 72 characters. See e.g. https://github.com/equinor/libecl/blob/4c45e6370ca8ed1b9bb0ad3c8a84facf636147e8/lib/ecl/ecl_smspec.cpp#L537-L540 This is not very easy to debug, especially as filepaths of both longer and shorter lengths are fairly common.

Ideally there shouldn't be a limitation to the filepath-length, and if it is kept, it should be longer, and with possibly with a warning if it is exceeded (at least mentioned in the documentation).

**Comment by joakim-hove** [comment]
Observe that this is an Eclipse limitation

**Comment by asnyv** [comment]
@joakim-hove No, it is not. Might have been at some point, but there is at least no problem for me now to run cases with longer paths in `RESTART`. Can investigate whether there is a new (longer) limitation.

**Comment by joakim-hove** [comment]
OK - corrected I stand

**Comment by asnyv** [comment]
@joakim-hove Actually, I just checked it. Seems like the **.SMSPEC** doesn't include more than 72 characters in the header, even though it is not a limitation in the `.DATA` file

**Comment by dotfloat** [comment]
This is a issue due to ECLIPSE's Fortran legacy. If this has been fixed by them then we can create a new issue which references their documentation.
