### ISSUE TITLE
"pip install ecl" does not install the whole packages

### ISSUE THREAD

**Issue by jt-qgc** [equinor/ecl#755]
I just tried to install ecl using command: pip install ecl, however there is nothing installed on .../site-package/ecl. Only _init_py in the folder. So, I can't import grid using python.

Early this month (10 Nov 2020), I did install the package and I can see in the .../site-package/ecl the following folders/files:
ecl, eclfile, grid, summary, util, well, etc..... everything worked fine until today when I tried to re-install.

Appreciate any advise... thank you

**Comment by jt-qgc** [comment]
additional information: the previous install was on linux workstation.
then I tried to reinstall the same using anaconda on windows 10.

**Comment by crayxt** [comment]
@jt-qgc There are no Windows wheels for ecl on pypi. What you have installed is ecl 0.0.0 which only contains the files you mentioned. You'll need to build wheel yourself.

**Comment by dotfloat** [comment]
Windows 10 is not supported right now. Closing due to the similar https://github.com/equinor/ecl/issues/726
