### ISSUE TITLE
ECLFile IO and Filelikes

### ISSUE THREAD

**Issue by mcgreen-origen** [equinor/ecl#763]
I'm trying to open an ECLFile using the byte stream I have on RAM. 

However, it looks like ECLFile is forcing me to save this to disk first and then provide a filepath. I suggest that filelike objects be added to acceptable inputs for ECLFile to avoid saving to disk only to load back into RAM.

Here is example code:
```
from io import BytesIO
from ecl.eclfile import EclFile

byte_stream = BytesIO()
# any cloud based client would suffice here
_client().download_fileobj(Bucket=bucket, Key=key, Fileobj=byte_stream)

# fails on this line currently, expecting a filepath, not a filelike object
timestep_file = EclFile(byte_stream)
swat_kw = timestep_file.iget_named_kw("SWAT", 0)
```

**Comment by dotfloat** [comment]
_ecl_ currently does not support anything that can't get converted into a C `FILE *`. We already have an issue on this: https://github.com/equinor/ecl/issues/732

You can try to write files to `/dev/shm` on Linux, which a filesystem located entirely in memory.
