### ISSUE TITLE
Relaxing the 8 character limit on grdecl keyword names

### ISSUE THREAD

**Issue by abingham** [equinor/ecl#775]
Is there any chance of relaxing the 8 character limit on keywords names in grdecl files? It seems quite common in practice to create keywords with longer names, and it's frustrating that they can't be opened with ecl. Perhaps the ``strict`` parameter to ``EclKW.read_grdecl()`` could allow longer names so that you have to opt-in to loading them.

**Comment by lars-petter-hauge** [comment]
Hi @abingham 

The hard limit of 8 characters originates from eclipse simulator being developed in FORTRAN, and as such anything from eclipse should be valid in those terms. Could I ask where you are getting the files that can not be opened with ecl from?

**Comment by abingham** [comment]
I'm pretty sure they're coming from RMS, but I'll let you know if that turns out to be incorrect.

**Comment by lars-petter-hauge** [comment]
But then you are not using eclipse (E100 or E300) to run the case.

What you are asking is then if libecl could allow for keywords longer than 8 in the input file, but simply ignore the content?

Did some testing here, and it seems it is a pretty hard failure when using longer characters - we can at least make sure it doesn't segfault.

**Comment by abingham** [comment]
> But then you are not using eclipse (E100 or E300) to run the case.

We're not actually running eclipse at all. The person I'm working with is using RMS to generate grdecl files because that's what she knows how to do and it's a fairly convenient format for the work we're doing.

> What you are asking is then if libecl could allow for keywords longer than 8 in the input file, but simply ignore the content?

I don't think that's what I'm asking, though perhaps we're talking past each other on technicalities. I'd like `EclKW.read_grdecl()` to accept longer keyword names and return the data it finds at that keyword in the file, i.e. I definitely don't want the content ignored.

It sounds like we're using ecl with a different emphasis than the intended use: we want to read (and write) grdecls because it's a useful format, not because we want to actually use eclipse.

**Comment by dotfloat** [comment]
Can you generate other formats? GRDECL is specific to Eclipse and there exist more widespread formats with much better support in the scientific computing community.

At the moment ecl is a program that reads and writes Eclipse files. If Eclipse can't read it, then it isn't in scope for this project. This could of course change soon (we'll have an internal discussion on this next year). But as it stands now there should be a really good reason to support something that Eclipse doesn't.

**Comment by abingham** [comment]
I'm not sure what the other output options are, but I'm sure we can sort something out. If this change is out of scope for ecl, then I'll close it up. Thanks!
