### ISSUE TITLE
Add .clang-format

### ISSUE THREAD

**Issue by dotfloat** [equinor/ecl#785]
We need to have a consistent code style for new C++ code.

**Comment by eivindjahren** [comment]
Would `clang-format -style=google -dump-config > .clang-format` suffice (it is what I used for the new test code)?

**Comment by dotfloat** [comment]
I am ok with this to start, although Google style is usually frowned upon. It's very specific to their company and we shouldn't follow it blindly. That said, if the format is reasonable, then sure. Reasonable would probably not include the weird indentation of
```c++
class Foo {
   public:
    Foo();
```
