### ISSUE TITLE
PIP install support for WINDOWS OS

### ISSUE THREAD

**Issue by SolaAbdulRDS** [equinor/ecl#808]
Support for pip installation of the ecl library on WINDOWS, i.e. no requirement for cmake and msvs as is currently the case.

**Comment by dotfloat** [comment]
Hi. The current state of the ecl Python Windows builds is that we still need to fix all the unit tests and have a Github Actions pipeline. I have it in my Todo list, but it's very low priority. Sorry.

Closing in favour https://github.com/equinor/ecl/issues/726
