### ISSUE TITLE
Value of returned summary timestamps affected by `lazy_load` parameter

### ISSUE THREAD

**Issue by sigurdp** [equinor/ecl#836]
```
import ecl.summary

# smry_filename = "../../gitRoot/webviz-subsurface-testdata/01_drogon_design/realization-0/iter-0/eclipse/model/DROGON-0.UNSMRY"
smry_filename = "DROGON-0.UNSMRY"

eclsum_lazy = ecl.summary.EclSum(smry_filename, lazy_load=True)
eclsum_eager = ecl.summary.EclSum(smry_filename, lazy_load=False)
lazy_dates = eclsum_lazy.numpy_dates
eager_dates = eclsum_eager.numpy_dates
print(f"len(lazy_dates)={len(lazy_dates)}")
print(f"len(eager_dates)={len(eager_dates)}")

for i in range(len(lazy_dates)):
    lazy_date = lazy_dates[i]
    eager_date = eager_dates[i]
    if lazy_date != eager_date:
        print(f"diff at idx={i}  lazy_date={lazy_date}  eager_date={eager_date}")
```

When I run the code snippet above, it results in different timestamps being returned for some of the array elements, seemingly  depending on whether `lazy_load` is set to `True` or `False`. 

My output from running the script looks like this:
```
len(lazy_dates)=244
len(eager_dates)=244
diff at idx=17  lazy_date=2018-03-24T10:24:58.000  eager_date=2018-03-24T10:24:59.000
diff at idx=23  lazy_date=2018-04-13T14:05:44.000  eager_date=2018-04-13T14:05:45.000
diff at idx=32  lazy_date=2018-05-11T20:27:28.000  eager_date=2018-05-11T20:27:29.000
diff at idx=33  lazy_date=2018-05-20T09:49:57.000  eager_date=2018-05-20T09:49:58.000
diff at idx=53  lazy_date=2018-07-15T02:10:29.000  eager_date=2018-07-15T02:10:30.000
diff at idx=54  lazy_date=2018-07-16T16:05:15.000  eager_date=2018-07-16T16:05:16.000
diff at idx=136  lazy_date=2019-05-12T05:21:14.000  eager_date=2019-05-12T05:21:16.000
diff at idx=182  lazy_date=2019-11-04T21:26:06.000  eager_date=2019-11-04T21:26:08.000
diff at idx=230  lazy_date=2020-05-08T03:18:22.000  eager_date=2020-05-08T03:18:24.000
diff at idx=231  lazy_date=2020-05-11T13:39:13.000  eager_date=2020-05-11T13:39:12.000
```

The attached test files are from the `webviz-subsurface-testdata` repository, specifically https://github.com/equinor/webviz-subsurface-testdata/tree/master/01_drogon_design/realization-0/iter-0/eclipse/model

The above behavior was observed using *Python* 3.8.5 and *ecl* version 2.13.0

[testfiles.zip](https://github.com/equinor/ecl/files/7454437/testfiles.zip)

**Comment by eivindjahren** [comment]
I am guessing this is a discrepancy in how the lazy loader and the normal loading handle seconds: https://github.com/equinor/ecl/blob/b1e9000d681417344cf7702aefc8e91d7a1421bf/lib/ecl/ecl_unsmry_loader.cpp#L81-L112
https://github.com/equinor/ecl/blob/b1e9000d681417344cf7702aefc8e91d7a1421bf/lib/ecl/ecl_sum_tstep.cpp#L149-L187

**Comment by BjarneHerland** [comment]
> I am guessing this is a discrepancy in how the lazy loader and the normal loading handle seconds:

Yes, also my current suspicion. Got sidetracked, will look at this on monday.

**Comment by BjarneHerland** [comment]
Should be fixed on master-branch now - @sigurdp: can you confirm?

**Comment by sigurdp** [comment]
> Should be fixed on master-branch now - @sigurdp: can you confirm?

I am currently consuming ecl as a Python package and unfortunately don't have my system configured for building ecl from source code. I will try it out and let you know as soon as a new PyPi package is released.

**Comment by dotfloat** [comment]
You can download the artifacts from here https://github.com/equinor/ecl/actions/runs/1444545642 (bottom of the page)

Unzip the correct one and `pip install ./[name].whl`

**Comment by sigurdp** [comment]
@dotfloat Thank you for the tip :-) 
I successfully downloaded and installed the artifact wheel and and I am happy to confirm that the fix seems to be working as expected.

**Comment by eivindjahren** [comment]
On this, It is weird that the implementation gets the time from the DOUBHEAD field instead of from the INTEHEAD fields representing time?
