### ISSUE TITLE
Internal error index: -1 on case when multiple using BASIC=6 and RPTONLY

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ecl#861]
The issue can be easily reproduced by using the `SPE1CASE1` from  https://github.com/OPM/opm-data. Set `BASIC` to 6 and include `RPTONLY`. Try to load the summary file and observe:

```
python -c "from ecl.summary import EclSum; ecl_sum = EclSum('SPE1CASE1'); ecl_sum.report_dates"
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Internal error when looking up index: -1
Aborted (core dumped)
```

**Comment by kvashchuka** [comment]
I am going through Eclipse reference manual and I am confused. 

According to it, if BASIC is set to 6:
`If set to 6, a Restart file is written at every timestep.`
And `RPTONLY` keyword means that 
`This keyword requests that summary data be written to the Summary file only at report times.`

I think the two contradict each other and therefore the error. Can it be so @lars-petter-hauge ?

**Comment by asnyv** [comment]
A restart step is a timestep, so the steps in the restart file are a subset of the steps in the summary file (which contains all timesteps).

I would assume that if you included both `RPTRST` with `BASIC=6` and `RPTONLY` within the same timestep in your eclipse input deck, the latest defined would matter, and if defined in different timesteps the first defined would govern the behavior until (and including) the date where the second keyword is defined in the schedule. But I haven' tested this specific combination of keywords, and Eclipse behavior isn't always as I expect...

**Comment by lars-petter-hauge** [comment]
It wasn't obvious figuring this out, and still I might be wrong..

So the unit we can choose from is `timestep` and `report time`. A `timestep` is whenever the simulator will complete its calculations and continue to the next time. It is the smallest temporal resolution available. A `report time` is specified by the user, a forced `timestep` that the simulator must include. All `report time` is also a `time step`, but not all `time step` is a `report time`.

The `RPTRST` and `RPTONLY` controls the output frequency of `RESTART` and `SUMMARY` files respectively. The typical behaviour is that we have more `SUMMARY` output than `RESTART`. Out of the 6 values of `BASIC` (sub argument of `RPTRST` which controls frequency), only value 6 will provide output more often than every `report time` (which will give every `time step`).

**Comment by lars-petter-hauge** [comment]
@kvashchuka and I did some more investigations as well, trying different settings and going through populating the index (`report_map` in `ecl_sum_file_data::TimeIndex`). I'll add it here in the issue for future reference.

```
SPE1CASE1_B6_RPTONLY (restart every timestep, summary every report step):
report_map[0] = {first: 2147483647, second: -1}
report_map[1] = {first: 0, second: 0}
report_map[2] = {first: 2147483647, second: -1}
report_map[3] = {first: 2147483647, second: -1}
report_map[4] = {first: 2147483647, second: -1}
report_map[5] = {first: 2147483647, second: -1}
report_map[7] = {first: 1, second: 1}
report_map[8] = {first: 2147483647, second: -1}


SPE1CASE1_B2_RPTONLY (restart every report step, summary every report step):
report_map[0] = {first: 2147483647, second: -1}
report_map[1] = {first: 0, second: 1} # initially second: 0
report_map[2] = {first: 2, second: 2}
report_map[3] = {first: 3, second: 3}
...

SPE1CASE1_B2 (restart every report step, summary every time step)
report_map[0] = {first: 2147483647, second: -1}
report_map[1] = {first: 0, second: 7} # <second> starts at 0 and is incremented by 1 to final value
report_map[2] = {first: 8, second: 9} # <first> populated with 8 and second with 8 at first iteration. second then bumped
report_map[3] = {first: 10, second: 10}
report_map[4] = {first: 11, second: 11}
report_map[5] = {first: 12, second: 12}


SPE1CASE1_B6 (restart every time step, summary every time step)
report_map[0] = {first: 2147483647, second: -1}
report_map[1] = {first: 0, second: 1} # initially second: 0
report_map[2] = {first: 2, second: 2}
report_map[3] = {first: 3, second: 3}
...
```

**Comment by asnyv** [comment]
Maybe a stupid question, but what is the "first" and "second" in this case?


Also:
> Out of the 6 values of BASIC (sub argument of RPTRST which controls frequency), only value 6 will provide output more often than every report time (which will give every time step).

I'm a bit unsure of whether it is _more often than every `report time`_? What is the exact definition of a `report time`? My impression is that a `report time` is a specific time that is forced based on the input and/or logic given in the setup, and not a time step that is based on convergence criteria only. So if you e.g. have defined that you should report to `RESTART` for every `time step`, that means in my head that the set of `report times` is equal to the set of `time steps`, and that you never should get in a situation where the `report times` are not also `time steps`? I might be wrong, as I cannot remember to have ever seen anyone use `RPTONLY`, and therefore in all my experience all time steps have been present in the `SUMMARY` file. But all restarts are based on defining the index of the report time you want to restart from, so I would assume that all steps when you write to the `restart` file are `report times` and thus also in the `SUMMARY` file independent of how you define it?

**Comment by lars-petter-hauge** [comment]
> Maybe a stupid question, but what is the "first" and "second" in this case?


I'll steal the ASCII drawing from the code documentation to make things easier to see:

```

                                                 S0001                                          S0002
   ||------|------|------------|------------------||----------------------|----------------------||
          M1     M2           M3                 M4                      M5                     M6
```

The M indicates a Ministep (which we have called a `time step` so far). while the `S` indicates a report step (as the summary files are named `S0001` and so forth when non-unified). The first report step consists of four ministeps, which in ecl is represented as a range, with `first` being `M1` and `second` being `M4` for report step `S0001`. The second report step will consist of `M5` and `M6`.

> a report time is a specific time that is forced based on the input and/or logic given in the setup, and not a time step that is based on convergence criteria only. 

I agree.

> So if you e.g. have defined that you should report to RESTART for every time step, that means in my head that the set of report times is equal to the set of time steps

I disagree. The definition of what a `report time` is does not change when specifying how often `RESTART` should be reported. If you define that you want `RESTART` information to be output every `time step`, you will likely receive more entries than number of `report time` (which is specifically set by the user)

> you never should get in a situation where the report times are not also time steps

It has not been stated that a `report time` is not also a `time step`, quite the opposite, we state that _every_ `report time` _is_ a `time step`.

> But all restarts are based on defining the index of the report time you want to restart from, so I would assume that all steps when you write to the restart file are report times and thus also in the SUMMARY file independent of how you define it?

True with the exception of when you are using `BASIC=6` - in which case the indexing will be based on `time step` instead (and you would have to check the `PRT` file to figure out which index you want to use).
