### ISSUE TITLE
Upgrade/pin or remove clang-format 14

### ISSUE THREAD

**Issue by hnformentin** [equinor/ecl#882]
Got an error message when running #881 that suggests that we need to do something about version of clang-format.

```
Run ./script/clang-format --check
Version of clang-format (clang-format) is 14, expected it to be one of 10, 11, 12
Error: Process completed with exit code 1.
```

**Comment by pinkwah** [comment]
Closing, was fixed: https://github.com/equinor/ecl/commit/86a803928968bb88a9e78954e4d260739cb97162
